const POINTS_FOR_CORRECT_ANSWER = 10;
const POINTS_FOR_SINGLE_HINT = 5;

export default {
    POINTS_FOR_CORRECT_ANSWER: POINTS_FOR_CORRECT_ANSWER,
    POINTS_FOR_SINGLE_HINT: POINTS_FOR_SINGLE_HINT
}